### ISSUE TITLE
Clang compilation error

### ISSUE THREAD

**Issue by miloyip** [amir-s/jute#1]
With Apple LLVM version 7.0.0 (clang-700.0.72),

```
jute.cpp:80:22: error: addition of default argument on redeclaration makes this constructor a
      default constructor
jValue::jValue(jType tp = JUNKNOWN) {
```

Related [discussion](http://stackoverflow.com/questions/18313509/default-argument-gcc-vs-clang)

I think a simple fix is to make another default constructor.

**Comment by dspachos** [comment]
jute.h:23

```
public:
jValue(jType);
jValue();
```

jute.cpp:80
```
jValue::jValue() {
    jType tp = JUNKNOWN;
}
jValue::jValue(jType tp) {
	this->type = tp;
}
```

**Comment by amir-s** [comment]
I don't really have time to fix the issues for now. Do you guys mind preparing a PR to address the compilation errors?

**Comment by amir-s** [comment]
fixed in https://github.com/amir-s/jute/pull/3
